#
# Build the slooh explorer and publish as a zip
#

name: Slooh Explorer

on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: set-version-assemblyinfo
      uses: dannevesdantas/set-version-assemblyinfo@v.1.0.0
      with:
        # Folder location to search for AssemblyInfo.cs/.vb files
          path: src
        # Version number to set on [AssemblyVersion] and [AssemblyFileVersion] attributes of AssemblyInfo.cs/.vb files
          version: 1.0.$GITHUB_RUN_NUMBER
    
    # Compile the solution
    - name: Compile solution
      run: dotnet build src\Slooh.sln -c Release -o output
