#
# Build the slooh explorer and publish as a zip
#

name: Slooh Explorer

on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: 1.1.${{ github.run_number }}

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Set version in assemblyinfo
      uses: dannevesdantas/set-version-assemblyinfo@v.1.0.0
      with:
        # Folder location to search for AssemblyInfo.cs/.vb files
          path: src
        # Version number to set on [AssemblyVersion] and [AssemblyFileVersion] attributes of AssemblyInfo.cs/.vb files
          version: "$VERSION.0"
    
    # Compile the solution
    - name: Compile solution
      run: dotnet build src\Slooh.sln -c Release -o output

    - name: Zip binaries
      uses: TheDoctor0/zip-release@0.6.2
      with:
        # Filename for archive
        filename: 'Binary.zip'
        # Base path for archive files
        path: output
        # Working directory before zipping
        # directory: # optional, default is .
        # List of excluded files / directories
        # exclusions: # optional, default is 
        # List of excluded files / directories with recursive wildcards (only applies on Windows with `zip` type)
        # recursive_exclusions: # optional, default is 
        # Tool to use for archiving
        type: 'zip'
      
